name: Unsigned APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
      	uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Unsigned releaseA APK
        run: |
          set -e
          VERSION=$(date -d "8 hour" -u +3.%y.%m%d%H%M)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          chmod +x gradlew
          ./gradlew assembleAppReleaseA --build-cache --parallel --daemon --warning-mode all

      - name: Collect APK
        run: |
          set -e
          mkdir -p "$GITHUB_WORKSPACE/apk"
          for file in $(ls $GITHUB_WORKSPACE/app/build/outputs/apk/*/*/*.apk); do
            mv "$file" "$GITHUB_WORKSPACE/apk/legado_unsigned_${VERSION}_$(basename "$file")"
          done

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: legado.unsigned.releaseA
          path: ${{ github.workspace }}/apk/*.apk
